function reviewGetAllReviewPlotTitles
%% reviewGetAllReviewPlotTitles
%
%   Looks for all plots with "supertitles" - as all plots generated by the
%   makeReviewPlot function have
%


reviewPlotHandles = findall(0,'Tag','suptitle');

for i = 1:length(reviewPlotHandles)
    reviewPlotTitles(i) = get(get(reviewPlotHandles(i),'Children'),'String');
end

% get(get(reviewPlotHandles(2),'Children'),'String')

end

function fig = getParentFigure(fig)
% if the object is a figure or figure descendent, return the
% figure. Otherwise return [].
while ~isempty(fig) & ~strcmp('figure', get(fig,'type'))
  fig = get(fig,'parent');
end