mdrt
hs.fig = tab3;
tgroup.SelectedTab = tab3;

parent = tab3;

%% Commodity Filter - Radio Button Panel Generation
        
    tbutBoxPos = [ 300  57  126 251 ];
        
    tbutPos = [ 16  211  94  23; ...
                16  183  94  23; ...
                16  155  94  23; ...
                16  127  94  23; ...
                16   99  94  23; ...
                16   71  94  23; ...
                16   43  94  23; ...
                16   15  94  23  ];
    
    tbutText = {    'RP1' ; ...
                    'LO2'; ...
                    'GN2'; ...
                    'GHe'; ...
                    'GN2'; ...
                    'ECS'; ...
                    'WDS'; ...
                    'HSS'; };
                
   tbutHandleNames = { 'ctbut1', 'ctbut2', 'ctbut3', 'ctbut4', ...
                       'ctbut5', 'ctbut6', 'ctbut7', 'ctbut8' };

            
    hs.panel_commodities =  uipanel(parent, ...
            'Title',        'Filter by Commodity', ...
            'Units',        'pixels', ...
            'Position',     tbutBoxPos ...
            );
    
    % Procedural handle object generation.
    for i = 1:numel(tbutHandleNames)
        
        % Would this be better as a handle array instead of named objects?
        hs.(tbutHandleNames{i}) = uicontrol(hs.panel_commodities, ...
                                        'Style',        'togglebutton', ...
                                        'String',         tbutText{i}, ...
                                        'Units',        'pixels', ...
                                        'Position',     tbutPos(i,:) ...
                                        );
        
    end
        
   
    
    
    
%% Procedure Filter - Check Box Panel Generation
        
    cbutBoxPos = [ 471-24  57  150 251 ];
        
    cbutPos = [ 10  211  130  23; ...
                10  183  130  23; ...
                10  155  130  23; ...
                10  127  130  23; ...
                %16   99  94  23; ...
                %16   71  94  23; ...
                %16   43  94  23; ...
                %16   15  94  23  
                ];
    
    cbutText = {    'MARS Operation' ; ...
                    'MARS Procedure'; ...
                    'Vechile Support'; ...
                    'HAS MARS UID'; ...
                    %'GN2'; ...
                    %'ECS'; ...
                    %'WDS'; ...
                    %'HSS'; ...
                    };
                
   cbutHandleNames = { 'ctbut1', 'ctbut2', 'ctbut3', 'ctbut4', ...
                       %'ctbut5', 'ctbut6', 'ctbut7', 'ctbut8' 
                     };

            
    hs.panel_opFilter =  uipanel(parent, ...
            'Title',        'Filter by Commodity', ...
            'Units',        'pixels', ...
            'Position',     cbutBoxPos ...
            );
    
    % Procedural handle object generation.
    for i = 1:numel(cbutHandleNames)
        
        % Would this be better as a handle array instead of named objects?
        hs.(cbutHandleNames{i}) = uicontrol(hs.panel_opFilter, ...
                                        'Style',        'checkbox', ...
                                        'String',       cbutText{i}, ...
                                        'Units',        'pixels', ...
                                        'Position',     cbutPos(i,:) ...
                                        );
        
    end
        
    
    
    
%% Results Display Controls Generation

    hs.listbox_results = uicontrol(parent, ...
                                    'Style',        'Listbox', ...
                                    'Position',     [30 57 220 201], ...
                                    'Value',        1, ...
                                    'String',       {''} );
                                
    hs.guiText = uicontrol(parent, ...
                            'Style',                'text', ...
                            'Position',             [30 258 220 15], ...
                            'HorizontalAlignment',  'left', ...
                            'String',               'Matching Data');

%% FD Search Box Generation

hs.searchBar = uicontrol(parent, ...
                            'Style',                'edit', ...
                            'Position',             [30 286 220 22],...
                            'HorizontalAlignment',  'left', ...
                            'String',               {''} );
                        

hs.guiText(end + 1) = uicontrol(parent, ...
                            'Style',                'text', ...
                            'Position',             [30 308 220 15], ...
                            'HorizontalAlignment',  'left', ...
                            'String',               'Matching Data');
                        
                        
%% Date Search Generation

hs.buttonStart = uicontrol(parent, ...
                            'Style',                'pushbutton', ...
                            'Position',             [30 330 90 22],...
                            'Tag',                  'startDate', ...
                            'String',               'Start Date' ...
                            );
                        
hs.buttonStop = uicontrol(parent, ...
                            'Style',                'pushbutton', ...
                            'Position',             [284 330 90 22],...
                            'Tag',                  'startDate', ...
                            'String',               'Stop Date' ...
                            );                        
                        
hs.editStart = uicontrol(parent, ...
                            'Style',                'edit', ...
                            'Position',             [120 330 150 22],...
                            'HorizontalAlignment',  'left', ...
                            'String',               {''} );
                        
hs.editStop = uicontrol(parent, ...
                            'Style',                'edit', ...
                            'Position',             [374 330 150 22],...
                            'HorizontalAlignment',  'left', ...
                            'String',               {''} );

hs.buttonSearch = uicontrol(parent, ...
                            'Style',                'pushbutton', ...
                            'Position',             [530 330 100 22],...
                            'String',               'Search by Date' );
                        
                        
                        
%% Search Buttons

hs.buttonQuickPlot = uicontrol(parent, ...
                            'Style',                'pushbutton', ...
                            'Position',             [26 10 120 43],...
                            'String',               'Quick Plot' );


hs.buttonQuickPlot = uicontrol(parent, ...
                            'Style',                'pushbutton', ...
                            'Position',             [158 10 120 43],...
                            'String',               'Configure Plots' );
