%% settings GUI figure handle

sfh = figure('Name','MARS DRT Settings');


    sfh.Position = [sfh.Position(1) sfh.Position(2) 560,160];
    sfh.NumberTitle = 'off';
    sfh.ToolBar = 'none';
    sfh.MenuBar = 'none';



%% UI Controls

ui_edit_dataRepo = uicontrol(sfh,'Style','edit',...
                                 'String','Data repository path',...
                                 'Units', 'normalized',...
                                 'Position',[0.35 0.7 0.55 0.2]);
                             
ui_edit_graphConfig = uicontrol(sfh,'Style','edit',...
                                 'String','graph configuration path',...
                                 'units', 'normalized',...
                                 'Position',[0.35 0.4 0.55 0.2]);


b1 = uicontrol(sfh,'Style','pushbutton', ...
                'String','Choose Folder',...
                'TooltipString','Select a folder that contains the data repository',...
                'Units','normalized',...
                'Position',[.1 .7 .2 .2]);
            
b2 = uicontrol(sfh,'Style','pushbutton',...
                'String','Choose Folder',...
                'TooltipString','Select a folder to contain graph configuration files',...
                'Units','normalized',...
                'Position',[.1 .4 .2 .2]);