function [ fd ] = newFD( input_args )
%newFD returns an fd structure populated with blanks.
%   

fd = struct('ID',           '',...
            'Type',         '', ...
            'System',       '', ...
            'FullString',   '',...
            'ts',           '',...
            'isValve',      false);

end

