function addAdvancedMenuToPlot( figureHandle )
%addAdvancedMenuToPlot adds a menu to plot windows
%

m = uimenu(figureHandle, 'Label', 'Advanced');

uimenu(m,   'Label',        'Export Figure', ...
            'Callback',     'filemenufcn(gcbf,''FileSaveAs'')', ...
            'Separator',    'off');
        
% -------------------------------------------------------------------------
uimenu(m,   'Label',        'Link Axes', ...
            'Callback',     @linkTimeAxes, ...
            'Separator',    'on');
        
uimenu(m,   'Label',        'Unlink Axes', ...
            'Callback',     @unlinkTimeAxes, ...
            'Separator',    'off');
        
% -------------------------------------------------------------------------
uimenu(m,   'Label',        'Manage Event Markers', ...
            'Callback',     @eventMarkerVisibilityTool, ...
            'Separator',    'on');

%TUP:the below uimenu item was added for a horizontal line plotter        
uimenu(m,   'Label',        'Horizontal Lines', ...
            'Callback',     @plotHorizLine, ...
            'Separator',    'off');        
      
uimenu(m,   'Label',        'Data Analysis', ...
            'Callback',     @MDRTbrushMenu, ...
            'Separator',    'off');

% -------------------------------------------------------------------------
uimenu(m,   'Label',        'Bug Reporting', ...
            'Callback',     @reportMDRTbug, ...
            'Separator',    'on');
        

end

