hs.fig = figure;

hs.master = uicontrol(hs.fig, 'Style', 'listbox', ...
                        'units',        'normalized', ...
                        ... 'Position',     [0.025 0.15 0.45 0.8], ...
                        'Position',     [ 0.05 0.525 0.9 0.40], ...
                        'Value',        1, ...
                        'Callback',     @updateSelectList);
                    
                    
hs.events = uicontrol(hs.fig, 'Style', 'listbox', ...
                        'units',        'normalized', ...
                        ...'Position',     [0.525 0.15 0.45 0.8], ...
                        'Position',     [0.05 0.1 0.9 0.4], ...
                        'Value',        1);
                    
hs.select = uicontrol(hs.fig, 'Style', 'pushbutton', ...
                        'units',        'normalized', ...
                        'Position',     [0.05 0.025 0.45 0.075], ...
                        'String', 'Use Selected', ...
                        'Callback',     @useSelectedEvent);
                    
hs.done = uicontrol(hs.fig, 'Style', 'pushbutton', ...
                        'units',        'normalized', ...
                        'Position',     [0.5 0.025 0.45 0.075], ...
                        'String', 'Export Milestones', ...
                        'Callback',     {@exportMilestones,'prompt'});
                    
hs.infoString = uicontrol(hs.fig, 'Style', 'text', ...
                        'units',        'normalized', ...
                        'Position',     [0.05 0.95 0.9 0.03], ...
                        'HorizontalAlignment', 'left', ...
                        'String', 'Human Readable Description');
                    

%% Contents of getUniqueEventsFromDelim function
[t, c1, c2, uc1, uc2] = getUniqueEventsFromDelim


%%
                    
                    
% hs.master.String = uc2;
hs.master.String = uc1;



setappdata(hs.fig, 't', t);
setappdata(hs.fig, 'c1', c1);
setappdata(hs.fig, 'c2', c2);
setappdata(hs.fig, 'uc1', uc1);
setappdata(hs.fig, 'uc2', uc2);
setappdata(hs.fig, 'hs', hs);
